action: more fixes for brokenness
Running the action currently fails with:

    Error: failed to create directory /images: mkdir /images: permission denied

The commit which introduced lvh images pull didn't take into
account that / is owned by ... root and therefore lvh won't be able to make
the directory. It also seems like the name of the image path has changed,
adjust that as well.

Signed-off-by: Lorenz Bauer <lmb@isovalent.com>