fix condition logic to check for inputs.verbose
The current logic was always "true" which caused the lvh provisioning to
fail with the error:
```
Error: unknown flag: --verbose
```

Signed-off-by: André Martins <andre@cilium.io>